### ISSUE TITLE
pictures do not load

### ISSUE THREAD

**Issue by BrixXare** [LiveHelperChat/lhc_messenger#26]
Not able to view pictures from client, not even to send pictures to client.

Thanks

**Comment by remdex** [comment]
Seems something changed in the app since last release. Meanwhile you can switch to plain text links by modifying 
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/modules/lhxml/chatssynchro.php#L47-L51

And leaving only 50 line.
