### ISSUE TITLE
Android XML Manifest

### ISSUE THREAD

**Issue by mspacemedia** [LiveHelperChat/lhc_messenger#3]
Imported project into latest Android Studio, added flutter SDK and dart SDK as per requirements.

```flutter build apk```

in terminal results in: lhc_messenger-master/android/app/src/ma
in/AndroidManifest.xml' Please ensure that the android manifest is a valid XML
document and try again.

As does trying to build using Android Studio - pubspec.yaml also has issues with the head tags

```
<<<<<<< HEAD
  path_provider: ^0.4.1
  async_loader: ^0.1.1
  intl: ^0.15.3
  firebase_messaging: ^4.0.0+1
  flutter_local_notifications: ^0.3.8
  rxdart: ^0.18.1
  after_layout: ^1.0.4
  http: ^0.12.0+1
=======
  path_provider: "^0.4.1"
  async_loader: "^0.1.1"
  intl: "^0.15.3"
  firebase_messaging: "^2.0.0"
  flutter_local_notifications: "^0.3.8"
  rxdart: "^0.18.1"
  after_layout: "^1.0.4"
>>>>>>> d4f4935ed4db3a8f8a1f1f1dfdd9e04685d0ae76```

**Comment by samapraku** [comment]
@mspacemedia 

Please use the dev branch. It is more recent

**Comment by mspacemedia** [comment]
Thanks @samapraku
