### ISSUE TITLE
Mobile Android app notification sound issue

### ISSUE THREAD

**Issue by PeopleInside** [LiveHelperChat/lhc_messenger#30]
This issue is about LHC app, is not my phone issue I'm sure of that.
Inside LHC there is no settings to decide how notification are managed so need to go on Android settings.

Android cannot know what is new message or new chat, is something that is managed by the app.
As reported here:
https://github.com/LiveHelperChat/livehelperchat/issues/1651

I had the issue that New Chat message are used also for visitor messages so when the app is in background and the user send a message it play every time the long ring tone used for new pending chat.

Have you tried to reproduce the issue?
I'm using Android 10 and Poco X3 Phone.

**Comment by PeopleInside** [comment]
IM checking

**Comment by remdex** [comment]
That's exactly what I'm talking there should be setting in mobile app, because phone itself tries to group just.

**Comment by PeopleInside** [comment]
OK tested more and my issue report is valid.
Please see the screenshot bellow:

![photo_2021-04-06_20-31-57](https://user-images.githubusercontent.com/5006150/113761000-3a1db700-9717-11eb-83b8-0064626bee58.jpg)

For understand where the issue is I given a different sound for each type of notification:
- New Messages
- **Information (info from server)**
- Varie
- New Chat
- New Messages

Seems only one of all this sound notification is always used **Information (info from server)**
This sound is played when there are new pending chat but also on every message visitor type if operator is with the chat in the background but in browser or in email app so in a different app.

If Information notification are turned off all notification will stop to work.

Seems there are different categories but did not work, just one category is used: Information for all notification so there is no distinction on notifications as other settings ( New Messages, New Chat, etc) are simply ignored.

![photo_2021-04-06_20-31-57](https://user-images.githubusercontent.com/5006150/113761625-f7101380-9717-11eb-940f-04cf086a7c3d.jpg)

The issue is: the only notification that is used and work for all is the information notification in evidence by the arrow in the above screenshot. This is used for new chat, new messages, etc... so I cannot customize sounds or notification for example of pending chat (new chat) and for the New message. 

In the Android notification various category are showed for the mobile app but just one is used and just one works.
Easy to test, I assigned a different sound for each notification.

Started a chat and the sound played was the information notification sound.
Put the chat mobile app in the background, written a message visitor side and again the sound played was information notification sound.

Disabled this notification and I did not get anymore notified of any new chat and of any messages.

**Comment by remdex** [comment]
It changes nothing. It's just grouping your phone does for you. Title and rest argument for notification are the same always from my side. The only proper change is to have option turn off/on new messages notifcatiins from mobile app itself.

**Comment by PeopleInside** [comment]
> It changes nothing. It's just grouping your phone does for you.

How my phone can know is a live chat app? This is the app that in some way give this informations to Android, I think.. so issue for me is in the mobile app.

> Title and rest argument for notification are the same always from my side.

Great so can you try to insert a different sound notification for all category notification than start a chat and hear what sound is played? Will be the information notification sound.

try to write as visitor side on the website and have the Android app in background like when you switch from live chat app to browser in Android. The sound of new message received by the visitor in the mobile app will be information notification sound.

Seems just one category is working: information notification sound. All other category: new chat, new message are ignored.

The issue is actually I cannot have a sound for new chat (new pending chat) who should be of 3/4 minutes that is different from the visitor message sound that should be not so long.

The app seems support just one notification sound also if Android show different notification category those are not working.
you cannot set a sound for new chat and another sound for new message: the sound that app play is always one, the same.

**Comment by PeopleInside** [comment]
Another try you can do is leave just information notification active and deactivate all other notification options.
Nothing will change, you will still receiving same notification for new chat and new messages, this confirm all other category are ignored so actually the app support only one notification sound for all.

**Comment by remdex** [comment]
I have nothing to add except what i already wrote. It's YOUR phone does groupinrg and these setting not lhc. Mobile app just need setting in the app directly turn on/ff new messages notifcations.

**Comment by remdex** [comment]
I have added support if you are disabled new messages sounds in back office you also won't receive notifications for a new messages.

**Comment by PeopleInside** [comment]
Umh.. so for don't hear the sound on mobile I need disable also on desktop (web)?
If so is not useful for me :( I don't wanna disable the sound.
Maybe I can consider to disable on mobile just for visitor message and this is because I can see is not possible to customize a different sound for new message and new chat on the Android mobile app. Settings are present but did not work.

**Comment by remdex** [comment]
You will have to wait untill mobile app will have separate setting for that itself

**Comment by PeopleInside** [comment]
OK so I will wait, thank you.
I'm asking if you tested on Android device the steps I suggested: put a different sound for each notification you find in app manager, live helper chat than test start a new chat and send a visitor message. For me notifications sound are broken.. just one works.. and I don't think is my phone.. anyway an option to disable visitor message sound will maybe resolve almost the issue I see facing on my device where the long sound for chat pending is used also for each visitor message that is sent to me.

Thank you remdex.

**Comment by remdex** [comment]
I repeat last time. Notifications are send the same, grouping done by your phone. In monile app nothing won't be changed.

**Comment by PeopleInside** [comment]
> In monile app nothing won't be changed.

I understood no other changes that add a button to silence notification for new message, will be done.

> Notifications are send the same, grouping done by your phone.

Is just strange for me I have no issues with other Android apps like Telegram or WhatsApp that manage also different notifications sound like single chat or group chat and with live helper chat just one sound category works, all other not for me.

> I repeat last time.

I think you don't need repeat this: i don't wanna stress you.
I'm happy to know a fix will be released for disable messages sound, just sad to see issues with notification grouping just only for live helper chat Android app.

Again thanks for your help.
Not need to reply, I will wait and understood your point. I don't know about how Android app are programmed so maybe I'm just not understanding. I don't believe the sound issue is a bug in my phone or Android, if you tested and all works fine it's ok.

Have a great day remdex :)

**Comment by remdex** [comment]
You have to update lhc to to avoid lhc sending messages.

**Comment by PeopleInside** [comment]
Hi @remdex,
I don't wanna stress with this but I still have this issue on mobile.

If I open Android, App, Live Helper Chat, Notifications
at the end of the page I see two notifications are supported:

- **New Messages**
- **Information**

On **New Messages** I have no sound set, all disabled
On **Information** I have a long sound like a phone call for alert me when a new chat is pending.

The issue is that Information notification is used for pending chat but also for each and every message unread with the screen off that visitor send to the mobile app. The result is that if I need ask the visitor to wait and turn off the phone for end my job before retake the chat, I get phone continuing ringing a long tone for each message that user type.

Something should be wrong with the LHC app as seems I'm unable to set a sound message for pending chat and a different sound for visitor messages.

![photo_2021-12-02_18-00-21](https://user-images.githubusercontent.com/5006150/144468167-c3913c6b-0ef6-4669-83fb-0f6057e4eb4c.jpg)

![photo_2021-12-02_18-00-25](https://user-images.githubusercontent.com/5006150/144468189-88da5a09-6d4b-4333-9db8-e410455ffff8.jpg)

Sound sad to read that seems you don't know how to fix or don't wanna change something in the app.
I need acept chat from mobile app than move to the browser to avoid the phone still ring.
It's a very stresfull issue.

I hope you can take time, also long, but try to test and resolve this maybe with some help.
Thanks anyway.

**Comment by remdex** [comment]
As I don't have enough experience in flutter, nothing won't be changed in the app at the moment. Learn flutter and do it yourself!

**Comment by remdex** [comment]
And as a tip most likely you won't need to modify mobile app and just follow
These are channels
```
https://github.com/LiveHelperChat/lhc_messenger/blob/fbfa719db19bea02b9f3efadccb8fb519233e5d1/lib/utils/local_notification.dart#L34
```

In PHP I don't set channel at the moment so you can try to debug and play yourself here
```
https://github.com/LiveHelperChat/livehelperchat/blob/master/lhc_web/lib/core/lhmobile/lhmobile.php#L355
```

It should be modified according to this by checking `$params['chat_type']` and setting appropriate channel :)
```
https://newbedev.com/how-to-specify-android-notification-channel-for-fcm-push-messages-in-android-8
```

This experiment for sure you can do :)

Here some info also 
```
https://stackoverflow.com/questions/58037761/set-fcm-channel-id-in-php-for-notifications
```

I'm waiting pull request from you now :D

**Comment by remdex** [comment]
3.90v and 1.7v android app required.
