### ISSUE TITLE
Unable to post message to online operator from Operators chat screen 

### ISSUE THREAD

**Issue by Husnain-Asharf** [LiveHelperChat/lhc_messenger#32]
- I am trying to post message to online operator that is showing online in operators tab but rest api giving error as following : 
![image](https://user-images.githubusercontent.com/40805304/152685216-2a400143-6e2f-4356-aac5-89da0c34624e.png)
- I can read incoming messages but cannot post to online operators.
- Same issue with operator and admin account.
- But I can post messages to vistors.
- Anyone tell me what can be reason.

Following are screenshots of chat screen

![image](https://user-images.githubusercontent.com/40805304/152685302-90c0e345-2079-4678-99fb-a35875e74d5e.png)

![image](https://user-images.githubusercontent.com/40805304/152685324-8b122a42-2b5d-43f5-9117-25c282646efb.png)

**Comment by remdex** [comment]
If you are using proper versions Rest API should output something from this file
```
modules/lhgroupchat/addmessage.php
```

Because this call does not have even `{error: true}` as output. So something not right in your environment.

**Comment by remdex** [comment]
I ques I found why you can't add a messages. I'll push update to lhc_web repository. Mobile app has nothing to do with that.

**Comment by remdex** [comment]
Apply this fix https://github.com/LiveHelperChat/livehelperchat/commit/8ab78983aab4688d3623e22b9a759d5852b3edce make sure you clear cache.

**Comment by Husnain-Asharf** [comment]
Thanks dear.

**Comment by remdex** [comment]
Also there is a new version now in the repository with more features - bot chats, and ongoing trigger alerts :)

**Comment by Husnain-Asharf** [comment]
ok. Thanks i will update

**Comment by Husnain-Asharf** [comment]
I tried with new typo fix but still I could not post message.

**Comment by remdex** [comment]
Sorry. but this time I can't help because it works here.

Operator has to have this permission.
```
'lhgroupchat', 'use'
```

**Comment by Husnain-Asharf** [comment]
Thanks. It's working, it was due to cache I thought I cleared the cache but it wasn't.
