### ISSUE TITLE
helpdesk widget for visitors in flutter

### ISSUE THREAD

**Issue by Husnain-Asharf** [LiveHelperChat/lhc_messenger#33]
Hi
- I want add help chat widget for visitors in flutter.
- How can I achieve this?
- Please can you guide me if it's possible.

**Comment by remdex** [comment]
At the moment it's not possible unless you incorporate webview in the flutter and use use embed code of LHC itself also incorporate some Rest API calls.

**Comment by remdex** [comment]
https://api.livehelperchat.com/#/
https://livehelperchat.com/demo-12c.html

**Comment by Husnain-Asharf** [comment]
Ok. If I use rest api for this purpose. Is there any api that i can use to start chat for visitors. As you are using in web. Because i am unable to find api end point  for visitor start chat.

**Comment by remdex** [comment]
Open your eyes...
https://api.livehelperchat.com/#/chat/post_restapi_chat

You should have your backend which would be sending these request and app should communicate with your backend directly..

**Comment by Husnain-Asharf** [comment]
Yes i saw this. I was thinking it was for admin or operators.

**Comment by Husnain-Asharf** [comment]
thanks
