### ISSUE TITLE
Audio and Video call is not working in App

### ISSUE THREAD

**Issue by neekunj2022** [LiveHelperChat/lhc_messenger#36]
![image](https://user-images.githubusercontent.com/98958429/168598565-6bc98e70-eb30-4858-bec5-c6f361a9242e.png)

Getting this green line only cant get audio and video

**Comment by remdex** [comment]
Correct, in the mobile app they are not supported yet. Pull request are welcome ;)

**Comment by N30** [comment]
My entire options does not work, hitting the bar on the left hand side pulls up an offcanvas/overlay from bottom that is empty. Sorry to put this here, I am pretty happy and amazed with the progress I had live helper chat many years ago and this is great. I just ended up here trying to figure out if it was just me or the mobile options don't work. I intend to use chat mostly and if need be the Chrome/Android mobile web version works with the video call. I can live without it.

**Comment by remdex** [comment]
Left option is only for canned messages suggestions, there isno files or audio video call support at the moment. So you expected what's not there yet.
