### ISSUE TITLE
Am not receiving notifications on Android or iOS for new chat (or anything except test notification)

### ISSUE THREAD

**Issue by Chluz** [LiveHelperChat/lhc_messenger#38]
Hi dev team, 

once again thank you for this great piece of open source software. 
I've setup a lot of the site_admin backend, its quite amazing how many options you make available to admins. 

In any case, I've followed the instructions on setting up the mobile apps here: https://doc.livehelperchat.com/docs/mobile#mobile-apps with both android and iOS. 
The mobile device notification setting is active. The individual notification settings per device session is also active, and the setup departments are correctly requesting that an operator take a new chat (with a site_admin notification correctly working). 

However, nothing is showing on the mobile apps. I am however able to get test notification, and I was able to get a operator private conversation notification as well. Is there a setting I missed to as for department chats to send mobile app notifications on operator assignment ?

Thanks  very much,

**Comment by remdex** [comment]
I have nothing to add than written here...
https://doc.livehelperchat.com/docs/mobile#live-notifications-testing
