### ISSUE TITLE
Service API List

### ISSUE THREAD

**Issue by 123artorux** [LiveHelperChat/lhc_messenger#39]
I'd like to ask if theres any mobile Backend side code shared ?
For example i saw xml/checkLogin api url in flutter codes and I am curious to see if I could see the code for the api

**Comment by remdex** [comment]
Most of the api is here
https://api.livehelperchat.com/#/

The missing request you will have to find just in flutter code itself and app. Yours mentioned is here https://github.com/LiveHelperChat/livehelperchat/tree/master/lhc_web/modules/lhxml
