### ISSUE TITLE
'isInitialRoute' named parameter missing throughout build (Dev & Master)

### ISSUE THREAD

**Issue by mspacemedia** [LiveHelperChat/lhc_messenger#6]
```
Compiler message:                                                       
lib/pages/loginForm.dart:354:58: Error: No named parameter with the name 'isInitialRoute'.
                  new RouteSettings(name: MyRoutes.main, isInitialRoute: true),
```

**Comment by samapraku** [comment]
@mspacemedia that is an issue caused by an update in the Flutter framework.
I have fixed that issue on my local machine. 

Let's say I try to upload a working apk by close of today for you.

**Comment by mspacemedia** [comment]
Hi @samapraku,

That would be great but maybe also push the change - I'm keen to get a handle on this app too if possible.

**Comment by samapraku** [comment]
Hi @mspacemedia,

I have pushed the updates to dev branch.

Refer to the readme on the extension page especially the section on the REST API setup.
https://github.com/samapraku/lhc_gcm_extension#important---rest-api-requirements
 
Apks uploaded here: https://github.com/samapraku/lhc_messenger/tree/dev/apk
