### ISSUE TITLE
FCM Token?

### ISSUE THREAD

**Issue by mspacemedia** [LiveHelperChat/lhc_messenger#7]
@samapraku,

Where can I change the Firebase API Token in the APK so that I can use my own Google Firebase Cloud Messaging account? 

Not sure the app should have them hard coded - in both the APK/Web server... Surely it means all messages and notifications are running through your account?

**Comment by samapraku** [comment]
You can replace the google-services.json file with your own and build an apk:
https://github.com/samapraku/lhc_messenger/blob/master/android/app/google-services.json

Then replace the google_api_key item value under fcm in the extension settings file.
https://github.com/samapraku/lhc_gcm_extension/blob/master/gcm/settings/settings.ini.php

**Comment by mspacemedia** [comment]
Done, just need to get the REST-API to work with my users - the app builds fine and the Firebase json is in place

**Comment by samapraku** [comment]
@mspacemedia You mentioned that you are unable to set permission for new users. That will be related with LHC web. I suggest you report it in the LHC forum to get assistance with that. 
I also provided the links to the REST API documentation in this comment
https://github.com/samapraku/lhc_messenger/issues/2#issuecomment-626909359

You can try directly with Postman to make sure the API works with the username and password

**Comment by remdex** [comment]
Closed because of inactivity. If someone is experiencing more issue just create a new issue.
