### ISSUE TITLE
Could not detect extension required...

### ISSUE THREAD

**Issue by mspacemedia** [LiveHelperChat/lhc_messenger#9]
Hi Samapraku,

Just tried the latest version of your compiled app - I get the error above. Yet the module is installed and LHC has those permissions set for the server I am attempting to connect to.

Any ideas?

**Comment by samapraku** [comment]
Hi @mspacemedia 
The code that checks whether the extension is installed uses the LHC REST API. It won't work for now without setting up the REST API. It's one of the reasons I haven't released the app to the playstore.

I am refactoring the app to make the REST API an optional requirement. 

You can check the steps here for configuring the REST API in LHC web:
https://github.com/samapraku/lhc_gcm_extension#important---rest-api-requirements

**Comment by mspacemedia** [comment]
Okay, I have actually followed those instructions three times on two clean installs and none work. Will the refactored app have an option to use a different firebase account too. So that messaging can be sent securely without going through an intermediary account?

**Comment by samapraku** [comment]
Hello @mspacemedia 

Sorry for the late reply. 

For the REST API, I suggest you test it out separately for the LHC web installation even before enable the extension. The REST API is based on main LHC web. It doesn't require this chat extension to work. If the REST API works then the extension will also work. If it doesn't then at least I will know where to troubleshoot from. There is the API documentation which you can test with Postman.

Concerning using different Firebase accounts, I do not see how that will be possible to do that from withing the app given that the Firebase is compiled with the apk using the google-services.json file without making any authentication related actions programatically. The only way I see for now is building your own apk using google-services.json from your firebase console.

If you have figured out a way to handle the different Firebase accounts within the app, I would be glad to know.

**Comment by remdex** [comment]
This issue should be solved as new version of the app does not require custom extension. It has to be min 3.40v

**Comment by mspacemedia** [comment]
That's such a shame as I switched to Tawk.to only last week…
